"""Reference runs of the idHands hit-reaction helpers from the user's own DOOMx64.exe under Unicorn (offline, read-only);
the oracle for crates/rancher_sim/src/handlayers/reactions.rs (notes: gamedata/re/HANDSLAYERS.md section 7).

usage: reactions_emu.py <exe> [--rust]
  dir:    0x140ccb790 (idAnimWebHandsDirectionalAnimator: yaw -> dir_2/4/8 index/blend scalars at +0x7d8..+0x7f8)
  yaw:    0x1402ee3e0 (idVec3::ToYaw: atan2(y, x) in degrees, wrapped to [0, 360))
  spring: 0x1409430e0 (idSpring<idVec1>::SetK(k, -1): critical damping) then 0x1409442f0 (Update(dt)) per frame
  --rust prints the results as Rust array literals (f32 bit patterns) for the unit tests.
"""
import struct, sys
from unicorn.x86_const import UC_X86_REG_XMM0, UC_X86_REG_XMM1, UC_X86_REG_XMM2
from handlayers_emu import Engine, HEAP, f2u, u2f

DIR_SCALARS = 0x140ccb790
TO_YAW = 0x1402ee3e0
SPRING_SET_K = 0x1409430e0
SPRING_UPDATE = 0x1409442f0
ANIM = HEAP + 0x1000          # fake idAnimWebHandsDirectionalAnimator (only +0x7d8..+0x7fc is touched)
VEC = HEAP + 0x3000
SPRING = HEAP + 0x3100
SENTINEL = 0x7fc0dead


class ReactEmu(Engine):
    def xmm(self, reg, f):
        self.mu.reg_write(reg, f2u(f))

    def dir_scalars(self, yaw):
        self.mu.mem_write(ANIM + 0x7d8, struct.pack("<10I", *([SENTINEL] * 10)))
        self.xmm(UC_X86_REG_XMM1, yaw)
        self.call(DIR_SCALARS, ANIM)
        return list(struct.unpack("<9I", self.mu.mem_read(ANIM + 0x7d8, 36)))

    def to_yaw(self, v):
        self.vec(VEC, v)
        self.call(TO_YAW, VEC)
        return self.mu.reg_read(UC_X86_REG_XMM0) & 0xffffffff

    def spring(self, k, target, pos, frames):
        # idSpring<idVec1> as idHandsHitReactions' ctor (0x140d878d0) leaves it: all 0, K 1, damping 2, mass 1.
        f = [0.0] * 12
        f[8], f[9], f[10] = 1.0, 2.0, 1.0
        self.mu.mem_write(SPRING, struct.pack("<12f", *f))
        self.xmm(UC_X86_REG_XMM1, k)
        self.xmm(UC_X86_REG_XMM2, -1.0)
        self.call(SPRING_SET_K, SPRING)
        self.mu.mem_write(SPRING, struct.pack("<2f", target, pos))
        rows = []
        for dt in frames:
            self.xmm(UC_X86_REG_XMM1, dt)
            self.call(SPRING_UPDATE, SPRING)
            rows.append(list(struct.unpack("<3I", self.mu.mem_read(SPRING, 12))))
        return rows


YAWS = [0.0, 1.0, 44.9, 45.0, 89.99, 90.0, 135.0, 179.5, 180.0, 180.5, 225.0, 269.0, 270.0, 300.0, 315.0, 359.9,
        -0.001, -1e-8, -30.0, -180.0, -225.0, 360.0, 400.0, 539.0, 12.345, 222.2]
VECS = [(1, 0, 0), (0, 1, 0), (-1, 0, 0), (0, -1, 0), (0.3, -0.7, 0.2), (-0.6, -0.1, 0.9), (0, 0, 1), (1e-39, 0, 1),
        (-1, -1e-30, 0), (0.123, 4.56, -7.0)]
SPRING_FRAMES = [1 / 60] * 40 + [0.1, 0.0085, 0.017, 0.0001, 0.05] + [0.016] * 20


def main():
    exe = sys.argv[1]
    eng = ReactEmu(exe)
    dirs = [(y, eng.dir_scalars(y)) for y in YAWS]
    yaws = [(v, eng.to_yaw(v)) for v in VECS]
    springs = [(k, t, p, eng.spring(k, t, p, SPRING_FRAMES)) for (k, t, p) in ((150.0, 90.0, 0.0), (150.0, -170.0, 185.0),
                                                                               (40.0, 10.0, 350.0))]
    if "--rust" not in sys.argv:
        for y, r in dirs:
            print("dir", y, [round(u2f(u), 5) for u in r])
        for v, r in yaws:
            print("yaw", v, u2f(r))
        for k, t, p, rows in springs:
            print("spring", k, t, p, [round(u2f(u), 4) for u in rows[-1]])
        return
    print("// generated by tools/reactions_emu.py from DOOMx64.exe (0x140ccb790, 0x1402ee3e0, 0x1409430e0 + 0x1409442f0)")
    print("// (input bits, output bits); inputs are f32 bit patterns so nothing is rounded twice")
    print(f"pub const DIR_SCALARS: [(u32, [u32; 9]); {len(dirs)}] = [")
    for y, r in dirs:
        print(f"    (0x{f2u(y):08x}, [" + ", ".join(f"0x{u:08x}" for u in r) + "]),")
    print("];")
    print(f"pub const TO_YAW: [([u32; 3], u32); {len(yaws)}] = [")
    for v, r in yaws:
        print("    ([" + ", ".join(f"0x{f2u(x):08x}" for x in v) + f"], 0x{r:08x}),")
    print("];")
    print("pub const SPRING_FRAMES: [u32; %d] = [" % len(SPRING_FRAMES) + ", ".join(f"0x{f2u(x):08x}" for x in SPRING_FRAMES) + "];")
    print("// (k, target, pos, [target, pos, vel] bits after each frame)")
    print(f"pub const SPRINGS: [(u32, u32, u32, [[u32; 3]; {len(SPRING_FRAMES)}]); {len(springs)}] = [")
    for k, t, p, rows in springs:
        print(f"    (0x{f2u(k):08x}, 0x{f2u(t):08x}, 0x{f2u(p):08x}, [" + ", ".join("[" + ", ".join(f"0x{u:08x}" for u in r) + "]" for r in rows) + "]),")
    print("];")


if __name__ == "__main__":
    main()
